//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.12 at 05:33:28 AM CET 
//


package com.example.activities;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.activities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.activities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddActivityRequest }
     * 
     */
    public AddActivityRequest createAddActivityRequest() {
        return new AddActivityRequest();
    }

    /**
     * Create an instance of {@link AddActivityResponse }
     * 
     */
    public AddActivityResponse createAddActivityResponse() {
        return new AddActivityResponse();
    }

    /**
     * Create an instance of {@link DeleteActivityRequest }
     * 
     */
    public DeleteActivityRequest createDeleteActivityRequest() {
        return new DeleteActivityRequest();
    }

    /**
     * Create an instance of {@link DeleteActivityResponse }
     * 
     */
    public DeleteActivityResponse createDeleteActivityResponse() {
        return new DeleteActivityResponse();
    }

    /**
     * Create an instance of {@link DeleteWorkshopRequest }
     * 
     */
    public DeleteWorkshopRequest createDeleteWorkshopRequest() {
        return new DeleteWorkshopRequest();
    }

    /**
     * Create an instance of {@link DeleteWorkshopResponse }
     * 
     */
    public DeleteWorkshopResponse createDeleteWorkshopResponse() {
        return new DeleteWorkshopResponse();
    }

    /**
     * Create an instance of {@link GetUsersForActivityRequest }
     * 
     */
    public GetUsersForActivityRequest createGetUsersForActivityRequest() {
        return new GetUsersForActivityRequest();
    }

    /**
     * Create an instance of {@link GetUsersForActivityResponse }
     * 
     */
    public GetUsersForActivityResponse createGetUsersForActivityResponse() {
        return new GetUsersForActivityResponse();
    }

    /**
     * Create an instance of {@link UserResponse }
     * 
     */
    public UserResponse createUserResponse() {
        return new UserResponse();
    }

    /**
     * Create an instance of {@link GetAllWorkshopsRequest }
     * 
     */
    public GetAllWorkshopsRequest createGetAllWorkshopsRequest() {
        return new GetAllWorkshopsRequest();
    }

    /**
     * Create an instance of {@link GetAllWorkshopsResponse }
     * 
     */
    public GetAllWorkshopsResponse createGetAllWorkshopsResponse() {
        return new GetAllWorkshopsResponse();
    }

    /**
     * Create an instance of {@link WorkshopResponse }
     * 
     */
    public WorkshopResponse createWorkshopResponse() {
        return new WorkshopResponse();
    }

}
